server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pyx-masterdata-db.postgres.database.azure.com:5432/pyx_masterdata_db
    username: pyxdbadmin
    password: Qaid@2025
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 600000
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: none # Changed from 'update' for production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false # Changed to false for production
    open-in-view: false
    properties:
      hibernate:
        format_sql: false # Changed to false for production
        use_sql_comments: false # Changed to false for production
        jdbc:
          batch_size: 50
          fetch_size: 50
          batch_versioned_data: true
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false

# CORS settings for dev
cors:
  allowed-origins: "https://pyxnetwork.com/,https://marketplace-dev-react-fvc8fygrefhcfkch.australiaeast-01.azurewebsites.net/,http://localhost:5173/,http://localhost:5174/,http://localhost:3000/"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    org.hibernate: WARN # Reduce Hibernate logging verbosity
    org.springframework: WARN # Reduce Spring logging verbosity for production
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

# Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html